#!/usr/bin/env bash
set -euo pipefail

# `nix build` wrapper script utilizing remote builders
flags=()

builders_config="${NIX_BUILDERS_CONFIG:-${HOME}/config/nix-builders.nix}"
if [ -f "${builders_config}" ]; then
	builders_string="$(env NIX_PATH="builders-config=${builders_config}" nix-instantiate --eval --json -E '
	let
	  mkBuilder = let
	    nullOr = e: v: if v == null then e else v;
	    dash = v: if v == null then "-" else toString v;
	    dashList = v: if (v == null || v == []) then "-" else builtins.concatStringsSep "," v;
	  in
	    { hostName
	    , system ? null
	    , systems ? null
	    , sshUser ? null
	    , sshKey ? null
	    , maxJobs ? null
	    , speedFactor ? null
	    , mandatoryFeatures ? null
	    , supportedFeatures ? null
	    , publicHostKey ? null
	    }:
	    assert (hostName != null && hostName != "");
	    builtins.concatStringsSep " " [
	      (if sshUser != null then "${sshUser}@${hostName}" else hostName)
	      (nullOr (dashList systems) system)
	      (dash sshKey)
	      (toString (nullOr 1 maxJobs))
	      (toString (nullOr 1 speedFactor))
	      (dashList ((nullOr [] supportedFeatures) ++ (nullOr [] mandatoryFeatures)))
	      (dashList mandatoryFeatures)
	      (dash publicHostKey)
	    ];

	  builders = import <builders-config>;
	in
	builtins.concatStringsSep "; " (map mkBuilder builders)
	' | jq -r '.')"

	flags+=(
		--builders "${builders_string}"
		--builders-use-substitutes
	)
fi

current_system="$(nix-instantiate --eval -E --json 'builtins.currentSystem' | jq -r '.')"
target_system="${current_system}"
orig_argv=( "${@}" )

while [ -n "${1:-}" ]; do
	arg="${1}"
	case "${arg}" in
		--expr)
			# Skip processing tons of text
			shift
			;;
		--system)
			shift
			target_system="${1}"
			;;
		--store)
			shift
			store_path="${1}"

			if ! [ "${store_path}" = "/nix/store" ] && [ "$(uname -s)" = "Darwin" ]; then
				# error: building using a diverted store is not supported on this platform
				flags+=(--max-jobs 0)
			fi
			;;
	esac
	shift
done

set -- "${orig_argv[@]}"

if ! [ "${current_system}" = "${target_system}" ]; then
	flags+=(--max-jobs 0)
fi

nix "${flags[@]}" "${@}"
