#!/usr/bin/env bash
set -euo pipefail

lines=()

debugImport="false"
if [[ $- = *x* ]]; then
	debugImport="true"
fi

loader="$(git rev-parse --show-toplevel)/lib/load-builders.nix"
builders_string="$(env NIX_PATH="${NIX_PATH:-}${NIX_PATH+:}loader=${loader}" nix-instantiate --eval --json -E 'import <loader> { debugImport = '"${debugImport}"'; }' --show-trace | jq -r '.')"

if [ -n "${builders_string}" ]; then
	lines+=("builders = ${builders_string}")
fi

if (( ${#lines[@]} )); then
	lines+=("${NIX_CONFIG:-}")
	# shellcheck disable=SC2155 # echo cannot fail in this context
	export NIX_CONFIG="$(IFS=$'\n'; echo "${lines[*]}")"
fi

if (( $# )); then
	exec "${@}"
fi
	
echo "${NIX_CONFIG:-}"
